### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by Gutem** [JohnCoates/CSSketch#3]
Is this in the Roadmap?
I already using it a lot in my project and have an library of mixins snippets.

**Comment by slightlytyler** [comment]
+1 for Sass support

**Comment by bomberstudios** [comment]
+1 for a generic way to plug your own preprocessor ; )

**Comment by ahmadkadhim** [comment]
+1

**Comment by Dimasmagadan** [comment]
+1

**Comment by arjunblj** [comment]
+1'ing generally isn't super useful after a couple -- it's clear this is something people want so better not to bombard @JohnCoates. John, is this something you want to take? I really want this and I've never worked with Sketch plug-ins, but I'm happy to take a stab if you have something in mind. :+1:

**Comment by rizqinizamil** [comment]
+1 :+1:

**Comment by JohnCoates** [comment]
I've taken a look at LibSass and it doesn't look like it would be too hard to implement into CSSketch. I'll be giving it a shot this weekend, since it's been widely requested.

**Comment by bomberstudios** [comment]
Yay! Thanks : )

**Comment by skolade** [comment]
Thanks @JohnCoates! Thanks for your hardwork and contribution to the Design and development community!

**Comment by itsluke** [comment]
Awesome stuff, really enjoying using it.

**Comment by corysimmons** [comment]
@JohnCoates Update on this? Also, possibility for supporting Stylus? :^)

**Comment by danielone** [comment]
+1 !!!!!!!!!!!!!!!!!!!!
@John Coates do this!!!!!

**Comment by corgus** [comment]
+1

**Comment by olehmelnyk** [comment]
+1

can you make it work with native .css file? So we could use ANY CSS pre/post processors with it!

**Comment by JohnCoates** [comment]
.scss and .sass files are now supported 😁

.css files have always been supported

**Comment by j-ordon** [comment]
Thanks, man! You should have a donate button somewhere – let me buy you a beer!

**Comment by WillNeill** [comment]
@JohnCoates - I second @j-ordon. Have been watching all the updates today with a big smile thinking about all the cool things I'll be trying with Sketch tomorrow. Let me buy you the second beer.

**Comment by danielone** [comment]
@JohnCoates  A big thank you as well and +1 on the buy me beer button. 

Folks watching this thread, I think there is still tremendous opportunity to better integrate CSS/SASS with sketch's workflow and ux design process. We may wish to open a separate thread to discuss where we see opportunities so we can build on top of @JohnCoates great work!

**Comment by danielone** [comment]
@JohnCoates  you may wish to update Readme that now have sass support

**Comment by JohnCoates** [comment]
Thanks @j-ordon, @WillNeill, and @danielone for the beer offers, much appreciated! 

More than I need beer I'd appreciate any comments or suggestions for my new project: Sketch documents represented by XML files. Right now it's really hard to collaborate with Sketch documents since they're opaque binaries. I'm working on a way to have Sketch documents in an open format that will lend itself to collaboration and version control systems such as Git.

More on that here: https://github.com/JohnCoates/SketchKit/issues/1

Also if anyone is interested in helping out on a UX kit or UI kit let me know! One of the first uses for this new way to collaborate on Sketch documents will be to make a collaborative version of these kits that I hope will reach a large audience.

@danielone: I'll update the Readme, thanks.

**Comment by WillNeill** [comment]
Yep, count me in @JohnCoates 

Have you seen [Protien.io](http://theprotein.io/)?

**Comment by JohnCoates** [comment]
@WillNeill no, I hadn't heard of protein. that seems like a cool project, thanks for the link!
